#!/bin/bash
# My first script

for k in $( seq 1 52 )
do
  screen_name=$"my_screen"
  screen -dmS $screen_name${k}

  cmd=$"time /home/cc/nvc/pin-2.14-71313-gcc.4.4.7-linux/intel64/bin/pinbin -p32 /home/cc/tools/nvc/pin-2.14-71313-gcc.4.4.7-linux/ia32/bin/pinbin -t obj-intel64//dcache.so -- /home/cc/NPB3.3-OMP-C/bin/mg.A.x";

  screen -x -S $screen_name${k} -p 0 -X stuff "$cmd"
  screen -x -S $screen_name${k} -p 0 -X stuff $'\n'

done
